#base image
FROM node:4.0.0-slim

# exclude npm cache from the image
VOLUME /root/.npm

#add files ad set workdir
COPY . /clltr
WORKDIR /clltr

#install dependecys
RUN apt-get clean && apt-get update && \
    apt-get install -y g++ python bzip2 libfreetype6 make libfontconfig curl git &&\
    npm install -g node-gyp && \
    npm install -g npm-check-updates && \
    npm install -g browserify && \
    npm install -g phantomjs && \
    npm install -g tape-run && \
    npm install

#set app port
EXPOSE 8282
