#base image
FROM node:0.12.6-slim

#add files ad set workdir
COPY . /clltr
WORKDIR /clltr

#install dependecys
RUN apt-get clean && apt-get update && \
    apt-get install -y g++ python bzip2 libfreetype6 make libfontconfig curl &&\
    npm install -g node-gyp && \
    npm install -g npm-check-updates@1.5.1 && \
    npm install -g browserify && \
    npm install -g phantomjs && \
    npm install -g tape-run && \
    npm cache clean && \
    npm install

#set app port
EXPOSE 8282
