version: '2'
services:

  webserver:
      build:
        context: .
        dockerfile: Dockerfile-WebServer
      depends_on:
        - webdev
      restart: always
      volumes:
      - ./dist:/usr/local/apache2/htdocs
      ports:
      - "8282:80"

  webdev:
      build:
        context: .
        dockerfile: Dockerfile-Development
      restart: always
      volumes:
      - ./bin:/clltr/bin
      - ./package.json:/clltr/package.json
      - ./client:/clltr/client
      - ./dist/:/clltr/dist
      command: npm run serve


