# base image
FROM mhart/alpine-node:latest

# exclude npm cache from the image
VOLUME /root/.npm

#add files ad set workdir
COPY . /clltr
WORKDIR /clltr

# add runtime for native compiling
RUN apk update && \
    apk add --update \
            --repository http://dl-3.alpinelinux.org/alpine/edge/main/ \
            --allow-untrusted \
            git python make g++ gcc krb5-dev

# install dependecys, but first set oberon as registry archive
RUN npm install -g node-gyp && \
    npm install -g nodemon && \
    npm install -g tape-run && \
    npm install -g phantomjs && \
    npm install

# remove runtime and cache
RUN apk del git python make g++ gcc krb5-dev && \
    rm -rf /tmp/* /var/cache/apk/* /root/.node-gyp

#set app port
EXPOSE 8282
